name: Build packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic    
          - i386_pentium4
          - x86_64
        sdk:
          - openwrt-22.03

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install clang
          latest_commit="$(curl -s https://api.github.com/repos/daeuniverse/daed-revived-next/commits/main | jq -r '.sha' | cut -b 1-7)"
          timestamp=$(curl -s https://api.github.com/repos/daeuniverse/daed-revived-next/commits/main | jq -r '.commit.author.date')
          formatted_timestamp=$(date --date="$timestamp" "+%Y-%m-%d")
          echo "version=$formatted_timestamp-$latest_commit" >> "$GITHUB_ENV"

      - name: Building packages
        uses: sbwml/openwrt-gh-action-sdk@go1.21
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-daed-next
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
          
      - name: Create release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: daed-web-${{ env.version }}
          allowUpdates: true
          tag: daed-web-${{ env.version }}
          commit: main
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: build/daed-web-${{ env.version }}.*

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: daed-web-${{ env.version }}
          allowUpdates: true
          tag: daed-web-${{ env.version }}
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
          artifacts: "bin/packages/${{ matrix.arch }}/packages_ci/*.ipk"

      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
