name: Build Web

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build System Setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools
          sudo npm install -g pnpm

      - name: Update Makefile
        run: |
          latest_commit="$(curl -s https://github.com/daeuniverse/daed-revived-next/commits/main | grep -E '"Copy the full SHA"' | awk -F 'value="' '{print $2}' | cut -b 1-7 | sed -n 1p)"
          latest_commit_full="$(curl -s https://github.com/daeuniverse/daed-revived-next/commits/main | grep -E '"Copy the full SHA"' | awk -F 'value="' '{print $2}' | cut -b 1-40 | sed -n 1p)"
          timestamp=$(curl -s https://github.com/daeuniverse/daed-revived-next/commits/main | grep -E -o 'datetime="[^"]+"' | sed 's/datetime="\([^"]\+\)"/\1/' | sed -n 1p)
          formatted_timestamp=$(echo $timestamp | sed -r 's/([0-9]{4})-([0-9]{2})-([0-9]{2}).*/\1-\2-\3-/')
          sed -i '/PKG_VERSION:/d' ./daed-next/Makefile
          sed -i "7 a PKG_VERSION:=$formatted_timestamp$latest_commit" ./daed-next/Makefile
          sed -i '/PKG_SOURCE_VERSION:/d' ./daed-next/Makefile
          sed -i "13 a PKG_SOURCE_VERSION:=$latest_commit_full" ./daed-next/Makefile
          echo "version=$formatted_timestamp$latest_commit" >> "$GITHUB_ENV"

      - name: Commit file
        run: |
          rm -rf build
          git config --global user.email simonsqiu@foxmail.com
          git config --global user.name SimonsQiu
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Build daed-revived-next
        run: |
          git clone https://github.com/daeuniverse/daed-revived-next build --depth=1
          cd build
          commit_id=${{ env.version }}
          pnpm install
          STANDALONE=1 pnpm build
          cp -a .next/standalone out
          cp -a .next/static out/.next/
          cp -a public out
          mksquashfs out daed-web-$commit_id.squashfs -comp xz
          tar Jcf daed-web-$commit_id.tar.xz out

      - name: Create release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: daed-web-${{ env.version }}
          allowUpdates: true
          tag: daed-web-${{ env.version }}
          commit: main
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: build/daed-web-${{ env.version }}.*

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{ github.repository }}
          retain_days: 1

      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Old Action Artifacts
        uses: heidi-pay/gha-delete-artifacts@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          days: 3
          max-artifacts-to-delete: 100
          dry-run: no

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
