name: Update PKG

on:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build System Setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools jq
          sudo npm install -g pnpm

      - name: Update Makefile
        run: |
          chmod 755 ./daed-next/files/daed-next.init ./luci-app-daed-next/root/etc/init.d/luci_daed-next ./luci-app-daed-next/root/etc/daed-next/daed-next_sub.sh ./luci-app-daed-next/root/etc/daed-next/dashboard.sh
          latest_commit="$(curl -s https://api.github.com/repos/daeuniverse/daed-revived-next/commits/main | jq -r '.sha' | cut -b 1-7)"
          latest_commit_full="$(curl -s https://api.github.com/repos/daeuniverse/daed-revived-next/commits/main | jq -r '.sha')"
          timestamp=$(curl -s https://api.github.com/repos/daeuniverse/daed-revived-next/commits/main | jq -r '.commit.author.date')
          formatted_timestamp=$(date --date="$timestamp" "+%Y-%m-%d")
          sed -i '/PKG_VERSION:/d' ./daed-next/Makefile
          sed -i "7 a PKG_VERSION:=$formatted_timestamp-$latest_commit" ./daed-next/Makefile
          sed -i '/PKG_SOURCE_VERSION:/d' ./daed-next/Makefile
          sed -i "13 a PKG_SOURCE_VERSION:=$latest_commit_full" ./daed-next/Makefile
          echo "version=$formatted_timestamp-$latest_commit" >> "$GITHUB_ENV"

      - name: Commit file
        run: |
          rm -rf build
          git config --global user.email simonsqiu@foxmail.com
          git config --global user.name SimonsQiu
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Cleanup Old Action Artifacts
        uses: heidi-pay/gha-delete-artifacts@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          days: 3
          max-artifacts-to-delete: 100
          dry-run: no

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
